name: chirp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^7.0.1
  peerdart: ^0.5.6
  logger: ^2.6.2
  device_info_plus: ^12.3.0
  provider: ^6.1.5
  get_it: ^9.2.0
  uuid: ^4.5.2
  shared_preferences: ^2.5.4
  crypton: ^2.2.1
  encrypt: ^5.0.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^10.0.0
  file_picker: ^10.3.8
  crypto: ^3.0.7
  emoji_picker_flutter: ^3.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dependency_overrides: 
  flutter_webrtc: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/stardust.png
    - assets/images/mystical_eye.png
