name: chirp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^7.0.1
  peerdart: ^0.5.6
  logger: ^2.6.2
  device_info_plus: ^12.3.0
  provider: ^6.1.5
  get_it: ^9.2.0
  uuid: ^4.5.2
  shared_preferences: ^2.5.4
  crypton: ^2.2.1
  encrypt: ^5.0.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^10.0.0
  file_picker: ^10.3.8

dependency_overrides: 
  flutter_webrtc: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/stardust.png
    - assets/images/mystical_eye.png
